FRONT-END-BOOTCAMP-PLUS-5/KNACK

prisma/schema.prisma

---
- payments 테이블에 approved_at, method, status, toss_payment_key 컬럼 추가 
-
---

[prisma] Payments 테이블 컬럼 추가 

---

prisma/schema.prisma

---
- prodcuts kor_name, eng_name column 명 추가 
- brands, categories kor_name, eng_name 추가 
-
---

[prisma] products column add

---

app/admin/layout.tsx
app/admin/products/page.tsx
app/admin/products/productsPage.module.scss
app/api/admin/products/route.ts
backend/admin/products/applications/dtos/ProductDto.ts
backend/admin/products/applications/usecases/CreateProductUseCase.ts
backend/admin/products/domains/entities/Product.ts
backend/admin/products/domains/repositories/ProductRepository.ts
backend/admin/products/repositories/PrProductsRepository.ts
backend/utils/prisma.ts
prisma/schema.prisma

---
- 어드민 상품등록 페이지 추가 (/admin/products)
- 어드민 상품등록 API 추가 (/api/admin/products)
- prisma user auth 테이블  provider unique 해제 
- prisma payments 테이블 tossPaymentKey unique 추가 
- prisma products 테이블 상품 컬럼명 변경 
- <img width="336" height="563" alt="image" src="https://github.com/user-attachments/assets/446499db-d4bb-43ce-a7be-391235d3e2ea" />

[feat] 어드민 상품등록 페이지, API 추가 및 prisma column 변경 

---

app/api/upload/route.ts
backend/payments/repositories/KnackPaymentRepository.ts
backend/uploads/domains/repositories/FileUploadRepository.ts
backend/uploads/infrastructures/repositories/S3FileUploadRepository.ts
backend/utils/constants.ts
constraint/auth.ts
next.config.ts

---S3 이미지 저장시 name만 저장하고 CloudFront에서 접근을 통해 보안성 확보 및 빠른 이미지 불러오기를 위함
- CloudFront CDN 연결 후 추가 
- 사용예시
```ts
`${STORAGE_PATHS.PREFIX}/${STORAGE_PATHS.PRODUCT.THUMBNAIL}/${DB_SAVED_FILENAME}`
```
-
---

[feat] S3 이미지 불러오기 기능 업데이트

---

prisma/schema.prisma

---
- order table paymentId nullable 추가
-
- ***
-
---

[prisma] order table paymentId nullable 추가

---

backend/payments/applications/dtos/CreatePaymentDto.ts

---
- paymentRepository 에 payment type null 추가 
-
-
---

[prisma] paymentRepository 에 payment type null 추가 

---

app/(user)/LayoutWrapper.tsx
app/(user)/saved/page.tsx
app/(user)/saved/saved.module.scss
app/api/likes/route.ts
app/api/products/[id]/route.ts
app/api/products/route.ts
backend/likes/applications/usecases/CreateLikesUseCase.ts
backend/likes/applications/usecases/GetLikesUseCase.ts
backend/likes/domains/repositories/LikesRepository.ts
backend/likes/repositories/PrLikesRepository.ts
backend/products/applications/usecases/GetIdsProductUseCase.ts
backend/products/domains/entities/Products.ts
backend/products/domains/repositories/ProductRepository.ts
backend/products/repositories/PrProductsRepository.ts
components/common/Flex/flex.module.scss
components/common/Flex/index.tsx
services/like/index.ts
services/products/index.ts
types/like.ts
types/product.ts

---
- 상품 좋아요 추가, 삭제, 불러오기 API 연결 
- common Flex 컴포넌트 align end 속성 추가 
- 상품 여러개 불러오는 api 수정 
-
---

[feat] save 상품 탭 부분 완성 

---

backend/likes/repositories/PrLikesRepository.ts
backend/search/infrastructure/repositories/PrProductsRepository.ts
prisma/schema.prisma

---
- like 테이블 product_likes 로 변경
- brand_likes 테이블 추가 
-
---

[prisma] like 테이블 product_likes 로 변경, brand_likes 테이블 추가 

---

app/(user)/saved/page.tsx
app/api/brand-likes/route.ts
backend/brand-likes/applications/dtos/BrandLikeDto.ts
backend/brand-likes/applications/usecases/CreateBrandLikesUseCase.ts
backend/brand-likes/applications/usecases/DeleteBrandLikesUseCase.ts
backend/brand-likes/applications/usecases/GetBrandLikesUseCase.ts
backend/brand-likes/domains/entities/BrandLikes.ts
backend/brand-likes/domains/repositories/BrandLikesRepository.ts
backend/brand-likes/repositories/PrBrandLikesRepository.ts
services/like/index.ts
types/like.ts

---
- 브랜드 좋아요 추가, 삭제, 조회 API
- API, 테스트 연결 추가 
-
---

[feat] 브랜드 좋아요 추가, 삭제, 조회 API, 테스트 연결 추가 

---

app/api/categories/route.ts
app/api/search/route.ts
backend/categories/applications/dtos/CategoryDto.ts
backend/categories/applications/usecases/GetCategoryUsecase.ts
backend/categories/domains/entities/Category.ts
backend/categories/domains/repositories/CategoryRepository.ts
backend/categories/repositories/PrCategoryRepository.ts
backend/search/infrastructure/repositories/PrProductsRepository.ts
components/search/SearchBottomSheet/SearchCategory.tsx
components/search/SearchBottomSheet/index.tsx
components/search/SearchBottomSheet/searchBottomSheet.module.scss
components/search/SearchCsrWrapper/index.tsx
components/search/SearchFilter/index.tsx
constraint/product.ts
services/category/index.ts
types/category.ts
utils/search/searchBottomSheetTab.ts
utils/search/searchFilter.ts

---
- 카테고리 데이터 불러오는 백엔드 코드 추가
- 상품리스트 필터 바텀시트에 카테고리 데이터 호출, ui 적용 
***
---

[feat] 상품리스트 필터 바텀시트 카테고리 작업

---

app/(user)/saved/page.tsx
app/api/cart/route.ts
backend/brand-likes/domains/entities/BrandLikes.ts
backend/brand-likes/repositories/PrBrandLikesRepository.ts
backend/cart/applications/usecases/CreateCartUseCase.ts
backend/cart/applications/usecases/GetCartUseCase.ts
backend/cart/domains/repositories/CartRepository.ts
backend/cart/repositories/PrCartRepository.ts
backend/orders/applications/usecases/CreateOrderUseCase.ts
backend/products/domains/entities/Product.ts
backend/products/domains/entities/RecentProduct.ts
backend/products/repositories/PrProductsRepository.ts
components/products/BottomFixButton/bottomFixButton.module.scss
components/products/BottomFixButton/index.tsx
components/products/BrandInfo/brandInfo.module.scss
components/products/BrandInfo/index.tsx
components/products/DefaultInfo/index.tsx
components/saved/BrandSave/index.tsx
constraint/saved.ts
types/cart.ts
types/like.ts
types/productDetail.ts

---
- 고정 유저 아이디 제거
- 상품상세, 최근본 상품, 브랜드 좋아요 카운트 수 추가 
-
---

[feat] 고정 유저 아이디 제거, 상품상세, 최근본 상품, 브랜드 좋아요 카운트 수 추가 

---

app/(user)/saved/page.tsx
backend/likes/domains/entities/Likes.ts
backend/likes/repositories/PrLikesRepository.ts
components/products/BottomFixButton/index.tsx
components/saved/BrandSave/index.tsx
components/saved/ProductSave/index.tsx
components/saved/RecentlySave/index.tsx
types/like.ts

---
- 상품 좋아요 리스트 불러오는 로직 수정 
-
---

[refactor] 상품 좋아요 리스트 불러오는 로직 수정

---

app/(user)/saved/page.tsx

---
- saved 페이지 상품 없을때 에러 처리 
-
---

[hotfix] ids null check

---

app/(user)/search/page.tsx
backend/search/infrastructure/repositories/PrProductsRepository.ts
components/common/BottomSheet/index.tsx
components/common/ProductCard/index.tsx
components/search/SearchProductList/index.tsx
components/search/SearchProductList/searchProductList.module.scss

---
- 바텀시트 onClose() 클린업 함수 추가
- 상품 리스트 데이터 없을 때 Empty 컴포넌트 위치 수정
- 상품 재고가 0 이거나 아예 없을 때 품절로 표시되도록 로직 개선, 
- 상품 리스트 바텀네비게이션에 가려져서 padding-bottom 추가  
- ***
-
---

[fix] 상품페이지 버그 개선

---

app/(user)/LayoutWrapper.tsx
app/(user)/my/address/page.tsx
components/common/Header/index.tsx
components/main/BannerSlide/index.tsx
components/main/MiddleBanner/index.tsx
components/main/MiddleBanner/middleBanner.module.scss
components/products/BottomFixButton/index.tsx
next.config.ts
store/cartStore.ts
utils/address/index.ts

---
- 주소록 메인 주소 안나오던것 수정
- 장바구니 추가할때 중복 상품 체크하는 로직 추가
- 장바구니 store 형식 변경
- 메인페이지 베너, 중간베너 슬라이드 index 부분 조정
-
---

[hotfix] 주소록 메인 주소 안나오던것 수정, 중복 장바구니 상품 검증 추가

---

app/api/cart/route.ts
components/main/RecentProducts/index.tsx
components/products/BottomFixButton/index.tsx
components/saved/ProductSave/index.tsx

--- #83 , #85 
- 상품 상세페이지 장바구니 담기, 구매하기 로그인 체크 추가
- 메인페이지 최근 본 상품 슬라이드 왼쪽 정렬
- saved 페이지 좋아요 크기 맞춤 
-
---

[hotfix] 상품 상세페이지 로그인 체크 추가 

---

app/(user)/products/[id]/page.tsx
app/(user)/products/[id]/productDetail.module.scss
app/api/products/recommend/route.ts
backend/products/applications/usecases/GetRecomendProducts.ts
backend/products/domains/entities/Products.ts
backend/products/domains/repositories/ProductRepository.ts
backend/products/repositories/PrProductsRepository.ts
components/products/DetailLayout/detailLayout.module.scss
components/products/DetailLayout/index.tsx
components/products/ProductDetailImage/index.tsx
components/products/Recommends/index.tsx
components/products/Recommends/recommends.module.scss
components/products/Tab/index.tsx
components/products/Tab/tab.module.scss
components/products/TextReview/index.tsx
services/products/index.ts
store/scrollStore.ts
types/product.ts

---
- 상품 상세 페이지 추천 상품 구간 추가
- 상세페이지 상품상세, 리뷰, 추천 탭 누르면 스크롤 이동하는 기능추가 
-
---

[feat] 상품 상세 페이지 추천 상품 구간 추가

---

components/products/DetailLayout/detailLayout.module.scss
components/products/Tab/tab.module.scss

---
- 상품 상세페이지 헤더 변경으로 인한 높이수정
- 탭부분 z-index 조정
-
---

[hotfix] 상품 상세페이지 헤더 변경으로 인한 높이수정, 탭부분 z-index 조정

---

components/products/BottomFixButton/bottomFixButton.module.scss
components/products/ReviewBottomSheet/reviewBottomSheet.module.scss

---
- 상세페이지 구매 버튼 z-index 조정
- 리뷰 바텀시트 크기 조정
-
---

[hotfix] 상세페이지 구매 버튼 z-index 조정, 리뷰 바텀시트 크기 조정

---

.github/ISSUE_TEMPLATE/기능-개발-이슈-탬플릿.md
.github/ISSUE_TEMPLATE/버그-보고-이슈-탬플릿.md

[feat] 이슈 탬플릿 설정 추가 

---

app/(user)/my/buying/[id]/page.tsx
app/(user)/my/buying/page.tsx
app/(user)/my/page.tsx
app/(user)/payments/success/page.tsx
app/api/payments/route.ts
backend/orders/applications/dtos/CreateOrderEntityDto.ts
backend/orders/applications/dtos/CreateOrderItemDto.ts
backend/orders/applications/usecases/CreateOrderUseCase.ts
backend/orders/repositories/PrOrderRepository.ts
backend/payments/applications/usecases/GetPaymentsbyUserIdUseCase.ts
backend/payments/domains/entities/Payment.ts
backend/payments/domains/repositories/PaymentRepository.ts
backend/payments/repositories/PrPaymentRepository.ts
components/my/buying/BuyingList/buyingList.module.scss
components/my/buying/BuyingList/index.tsx
types/order.ts
types/payment.ts

--- #120 
- 결제정보 스냅샷 으로 바꾸고 나서 주문 내역 안불러와  지던것 수정 했습니다.
- orders 테이블에 paymentId 안들어가던 로직 수정 했습니다.
- 역시나 동일한 prettier 이슈...
-
---

[hotfix] 마이페이지 주문 내역 불러오는것 수정 
